param(
    [string]$EnvFile = "config.env",
    [string]$OutputFile = "config.h"
)

$map = @{
    "SUPABASE_HOST" = ""
    "SUPABASE_ANON_KEY" = ""
    "SUPABASE_SERVICE_KEY" = ""
    "DISCORD_HOST" = ""
    "DISCORD_PATH" = ""
}

if (!(Test-Path $EnvFile)) { Write-Error "Missing $EnvFile"; exit 1 }
Get-Content $EnvFile | Where-Object { $_ -match '^(\w+)=(.+)' } | ForEach-Object {
    $null = $_ -match '^(\w+)=(.+)'
    if ($map.ContainsKey($matches[1])) { $map[$matches[1]] = $matches[2] }
}

$missing = $map.Keys | Where-Object { [string]::IsNullOrEmpty($map[$_]) }
if ($missing) { Write-Error "Missing values: $($missing -join ', ')"; exit 1 }

$keyBytes = @()
$rng = [System.Random]::new()
for ($i = 0; $i -lt 64; $i++) {
    $keyBytes += $rng.Next(0, 256)
}

function XorEncrypt {
    param([string]$s, [byte[]]$key)
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($s)
    $result = @()
    for ($i = 0; $i -lt $bytes.Length; $i++) {
        $result += $bytes[$i] -bxor $key[$i % $key.Length]
    }
    return $result
}

$keyArrayStr = ($keyBytes | ForEach-Object { "0x{0:x2}" -f $_ }) -join ", "

$lines = @(
    "// Auto-generated by encrypt_config.ps1 -- do not edit",
    "#ifndef CONFIG_H",
    "#define CONFIG_H",
    "",
    "static const unsigned char g_configKey[64] = { $keyArrayStr };",
    "",
    "static std::wstring DecryptW(const unsigned char* data, size_t len) {",
    "    std::string tmp;",
    "    tmp.resize(len);",
    "    for (size_t i = 0; i < len; i++)",
    "        tmp[i] = data[i] ^ g_configKey[i % 64];",
    "    int wlen = MultiByteToWideChar(CP_UTF8, 0, tmp.c_str(), (int)len, NULL, 0);",
    "    std::wstring out((size_t)wlen, 0);",
    "    MultiByteToWideChar(CP_UTF8, 0, tmp.c_str(), (int)len, &out[0], wlen);",
    "    return out;",
    "}"
)

foreach ($key in $map.Keys) {
    $enc = XorEncrypt -s $map[$key] -key $keyBytes
    $arrStr = ($enc | ForEach-Object { "0x{0:x2}" -f $_ }) -join ", "
    $lines += "static const unsigned char _enc_$key" + "[] = { $arrStr };"
}

$lines += @(
    "",
    "#endif"
)

Set-Content -Path $OutputFile -Value ($lines -join "`r`n")
Write-Output "Generated $OutputFile"
